### ISSUE TITLE
Incorrect elements positioning on back swipe (iOS17 specific)

### ISSUE THREAD

**Issue by faljabi** [kirillzyusko/react-native-keyboard-controller#243] opened 2023-09-20 21:16 UTC
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/82410405/5dbce931-80cb-461e-926f-4e90f6c5556b
After updating to iOS17 I noticed that the keyboard height when using useKeyboardAnimation is behaving weird thus the content just above the keyboard is not really matching the height of the keyboard when using the back gesture. It was working fine with iOS16. Please see the attached video.

I am using the same example for the useKeyboardAnimation hook from the docs.

**Comment by kirillzyusko** [comment] 2023-09-21 06:54
Hello @faljabi 

I'm not able to reproduce it using example app (though I'm using beta version of iOS 17 simulator):

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/5df4ee96-f5d1-4c36-b6ef-3cffb8ad9449

Could you please add a small code snippet that I can use in example app to reproduce your problem? 🙏 
And also provide more information - are you using simulator? If yes, then is it a release version or a particular beta version?

Thanks in advance!

**Comment by faljabi** [comment] 2023-09-21 20:29
Hi @kirillzyusko 

First thank you for your reply and for this amazing module.

The video you attached the keyboard is being dismissed as you start swiping maybe that is why it is not happening with you. I am using react navigation native stack where keyboard does not really get dismissed. I guess maybe you are using the stack navigator and not the native stack I am using.

I tested on both a physical and emulator running iOS17. Both having the same issue. I want to pay your attention that I think it is not the module issue rather it is react navigation issue OR it is an OS issue because other apps having weird keyboard issue on back gesture. For example, Tiktok app has the same issue where the keyboard jump all over the screen when using the back gesture. This explains that my email domain suggestions jumping all over the screen as I swipe. So your module is returning the correct height and progress really! Please check the attach video. 

Sorry for wasting your time.

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/82410405/04cbbd14-39f6-41f0-9385-f6c9d2af96a1

**Comment by kirillzyusko** [comment] 2023-09-21 20:56
> Please check the attach video.

@faljabi I've also seen such behavior (and wrote a reproducible demo with such behavior in example app).

And definitely flying keyboard over a screen is OS bug (or maybe other modules produces such behavior, because I've disabled RNKC and the issue was still reproducible).

The one thing is that I don't understand - on your first video keyboard has static position. When you do swipe - your custom UI elements are moving vertically.

Could you test what happens if you specify hardcoded value for translateY (like 336 or a value close to your keyboard height) and don't use `useKeyboardAnimation` hook anymore. How UI will behave if you do a back swipe? Will it still be moving on his own or it will have static position?

Just want to understand whether it's still a problem of OS or this module has some problems as well 👀

**Comment by faljabi** [comment] 2023-09-21 21:18
I just tried with a static position and yes it is fixed right there at that static position with the keyboard having static position too if I start swiping back. I believe it is an OS issue because just 3 days ago was working fine before I upgraded to iOS17. I also updated today to 17.0.1 and still issue is there. I thought they fixed it.

I replaced

const { height, progress } = useKeyboardAnimation();

<Animated.View style={{
            transform: [{ translateY: height }],
            opacity: progress
        }}>

TO:        

 <View style={{
            position: 'absolute',
            transform: [{ translateY: 366 }]
        }}>

**Comment by dayze** [comment] 2023-09-22 08:43
this issue might be related 
https://github.com/facebook/react-native/issues/39411

**Comment by kirillzyusko** [comment] 2023-09-22 14:14
@faljabi @dayze Finally I could reproduce this problem! I did more investigation and it's really strange thing 🤯 

First of all keyboard becomes invisible for a fraction of a second:

|Start swipe|First frame after swipe|
|-----------|----------------------|
|<img width="1252" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/9a460952-1e75-484e-a4d3-2eb1ee3de2a0">|<img width="1249" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/ebc58fd0-fb5c-48ec-bbb9-c45736689958">|

And it triggers 2 (or 3?) events (pay an attention to weird `duration` value - before on iOS it was `0` or `250`):

<img width="1252" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/60121dde-a0d6-43d8-a842-c5c9178e97e0">

I've decided (just for experimenting purposes) add a guard in all keyboard handlers:

```tsx
      if (e.duration === 350) {
        return;
      }
```

To prevent any updates of shared values for this strange event... And unexpected result -> `TextInput` is not moving to top!

<img width="419" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/ea17b742-1eb7-4dd8-8ea5-aec8e02ac489">

The remaining content still moving to top (but it's not managed by RNKC - I use default RN methods for moving it above keyboard).

My initial impression is that these two random events act as detectors to identify a layout that depends on keyboard events and after that it moves this layout by OS (that's just an assumption) - because I don't receive any other events when I'm moving my finger. I think it's OS bug and I think it should be fixed by OS itself.

@hirbod I know you experience this problem too. Just decided to tag you, since this comment can be useful for you too.

**Comment by faljabi** [comment] 2023-09-24 21:35
@kirillzyusko yes I suspected that it is an OS bug or react navigation bug for sure. I noticed that most RN apps have the same issue on screens with modal presentation. I think if you use a card presentation for the screen the issue disappears.

Let's wait for a couple of OS updates and for sure I will keep you updated.

**Comment by kirillzyusko** [comment] 2023-09-25 08:39
> yes I suspected that it is an OS bug or react navigation bug for sure.

Yes, I have the same feeling. Let's keep this issue open and yes, please, keep me updated 🙌

**Comment by hirbod** [comment] 2023-09-25 10:09
Definitely an OS bug. Same issue happening on the native Slack iOS App. Guess it matters how keyboard / input is implemented for this issue to happen. 17.0.1 was released, need to check if that issue was fixed with that bugfix release.

**Comment by faljabi** [comment] 2023-10-04 21:02
I just want to give a little update. I enabled fullScreenGestureEnabled on my native stack navigator via screenOptions and now the issue is even more clear why the keyboard height is acting weird. When it was disabled the keyboard kept looking static. 

Please check the attached video. It now explains why my domain suggestions element is jumping overall the screen.

One more note: I updated to iOS17.0.2 and the issue is still there. 

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/82410405/72466c73-fcd1-40cd-919b-025372cbe24

**Comment by kirillzyusko** [comment] 2023-10-05 08:49
@faljabi yep, I had the same problem. In my understanding it's iOS problem (or maybe RNS). It's weird that the keyboard can fly over a screen 😔 

Let's wait for iOS 17.1 update - maybe it'll be fixed there 🤷‍♂️

**Comment by kirillzyusko** [comment] 2023-10-13 16:29
@faljabi @dayze @hirbod some good news, I've tested on iOS 17.1 beta 3 on iPhone 11. Here is results:

|fullScreenGestureEnabled: true|fullScreenGestureEnabled: false|
|-------------------------------|--------------------------------|
|<video src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/39561101-855c-4c14-8de8-6595bcf9ef6d">|<video src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/e280305a-7077-4410-b6f6-1c7c7ad94962">|

`fullScreenGestureEnabled: false` still buggy (unneccessary input movement + keyboard flash in the end), but good to know that Apple is aware about issues and fixing it 👀

**Closed** 2023-10-25 23:51 UTC
Labels: 🐛 bug, wontfix, 🍎 iOS

**Comment by hirbod** [comment] 2023-10-26 15:09
iOS 17.1 was released and the issue is gone! Great

**Comment by kirillzyusko** [comment] 2023-10-26 15:15
@hirbod did you test with `fullScreenGestureEnabled: true`? Have you had a chance to test with `fullScreenGestureEnabled: false`?

**Comment by hirbod** [comment] 2023-10-26 16:01
I tested with fullscreenGestureEnabled, yes. Will try without and report back later. @kirillzyusko
