### ISSUE TITLE
UseKeyboardHandler sometimes not reporting keyboard height

### ISSUE THREAD

**Issue by ImBeCiliC** [kirillzyusko/react-native-keyboard-controller#293] opened 2023-12-12 13:26 UTC
**Describe the bug**
When navigating to a new screen. Lets say a flow of Screen 1 Name and Screen 2 Surname with a React Navigation prop of keyboardHandlingEnabled `<StackNavigator.Screen name='Name' component={Name} options={{ keyboardHandlingEnabled: false }} />` to keep the keyboard open between screens sometimes leads to non reported values of the useKeyboardHandler on Android.

I update the height on all possible states and init the function on screen mount:     
```
const useKeyboardAnimation = () => {
    console.log('update keyboardHeight');
    const height = useSharedValue(0);
    useKeyboardHandler({
    onStart: (e) => { 
        'worklet';

         height.value = e.height;
    }

    onMove: (e) => { }

    onInteractive: (e) => { }

    onEnd: (e) => { }
}

const MoveOnKeyboardOpen = ({ children }: any) => {
    const { height } = useKeyboardAnimation();
    [...]
}
```

The screen uses this component to wrap specific elements that should move above the keyboard to make them visible or move towards the keyboard to have all elements within the same scope.

When i navigate between those screens back and forth on every 2/3/4 navigations the second screen is receiving a height of 0.

**Expected behavior**
That the value updates on all circumstances on navigation and is not skipped

**Smartphone (please complete the following information):**
 - Device: [Pixel 7]
 - OS: [Android]
 - RN version: [0.72.6]
 - RN architecture: [old]
 - JS engine: [Hermes]
 - Library version: [1.9.5]

Thanks for the help and for the package solved a lot of keyboard struggle i had. 
One thought that came while writing this report. Could this be caused due to the fact that onInteractive reports the new values instead of the other options and on android this option is not working without a KeyboardGestureArea

**Comment by kirillzyusko** [comment] 2023-12-12 13:51
@ImBeCiliC may I kindly ask you to provide a reproduction example?

And on which Android versions do you see this problem? Does it happen only on Android 11+ or does it happen on lower android versions as well?

**Comment by dppo** [comment] 2024-01-04 12:07
Encountered the same problem on the Android11 ​​emulator, when entering a new page in react-navigation, the first pop-up keyboard appeared
```
const useAnimatedKeyboardProgress = () => {
  const progress = useSharedValue(0);

  useKeyboardHandler(
    {
      onMove: e => {
        'worklet';
        progress.value = e.progress;
      },
    },
    [],
  );

  return progress;
};
```

**Comment by dppo** [comment] 2024-01-04 12:19
> Encountered the same problem on the Android11 ​​emulator, when entering a new page in react-navigation, the first pop-up keyboard appeared
> 
> ```
> const useAnimatedKeyboardProgress = () => {
>   const progress = useSharedValue(0);
> 
>   useKeyboardHandler(
>     {
>       onMove: e => {
>         'worklet';
>         progress.value = e.progress;
>       },
>     },
>     [],
>   );
> 
>   return progress;
> };
> ```

Also have the same problem on Android13 emulator

**Comment by kirillzyusko** [comment] 2024-01-04 13:31
@dppo may I kindly ask you to prepare/provide a small reproduction example?  In this case I'll be able to help you 😊

**Comment by dppo** [comment] 2024-01-04 15:58
> @dppo may I kindly ask you to prepare/provide a small reproduction example? In this case I'll be able to help you 😊

Thanks Reply

[This is a reproduction example](https://github.com/dppo/RNKCDemo)

I found that this problem can be reproduced when `initialRouteName={'Tab'}` is set, but if it is set to `initialRouteName={'Home'}`, this problem does not occur

I think this might have something to do with `@react-navigation/bottom-tabs`

**Comment by kirillzyusko** [comment] 2024-01-04 17:10
@dppo the problem in your example is that view is not getting resized on first keyboard appear?


https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/8723164a-981b-415d-bce9-f8ebaae37b76

**Comment by dppo** [comment] 2024-01-05 01:03
> ```tsx
> console.log("progress", progress.value);
> ```

You are right, this should have nothing to do with `react-native-keyboard-controller`, I think it may be related to `@react-navigation/bottom-tabs`, when I set `tabBarHideOnKeyboard: false`, this will appear question. But when set to `tabBarHideOnKeyboard: true`, this problem will not occur.

Thank you for your patient reply

**Comment by kirillzyusko** [comment] 2024-01-05 11:19
@dppo you're welcome. You're saying that the another issue could be reproducible if I set `tabBarHideOnKeyboard: false`?

**Comment by dppo** [comment] 2024-01-05 13:48
> @dppo you're welcome. You're saying that another issue could be reproducible if I set `tabBarHideOnKeyboard: false`?

The default value of `tabBarHideOnKeyboard` in `@react-navigation/bottom-tabs` is `false`, which will cause the problem in the example. However, if `tabBarHideOnKeyboard` is set to `true`, the problem in the example can be solved.

**Comment by kirillzyusko** [comment] 2024-01-07 16:16
> The default value of tabBarHideOnKeyboard in @react-navigation/bottom-tabs is false, which will cause the problem in the example. However, if tabBarHideOnKeyboard is set to true, the problem in the example can be solved.

Got it, but we found out that it's not a problem of RNKC, right? But actually it's very strange that the value of this prop can cause such problems 🤷‍♂️

**Comment by kirillzyusko** [comment] 2024-01-11 08:31
I'm going to close this issue due to missing repro, inability to reproduce it in my example app and beginning of mixing different problems into a single one.

If someone faces this problem - please, create a new issue (possibly with link to this issue) and prepare a reproduction example 🙏

**Closed by kirillzyusko** 2024-01-11 08:31 UTC
Labels: 🐛 bug, 🤖 android
