### ISSUE TITLE
TextInputs' are not pressable in the KeyboardStickyView example after scroll.

### ISSUE THREAD

**Issue by NodoPopkhadze** [kirillzyusko/react-native-keyboard-controller#457] opened 2024-05-30 13:54 UTC
**Describe the bug**
In the AwareScrollViewStickyFooter example of the react-native-keyboard-cotroller, TextInput components become unresponsive after scrolling when using Fabric architecture on Android real devices. This issue also extends to other touchable components in my project.

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/47716245/9186ba3c-f7ac-414b-83ac-5d3e692ca691

**To Reproduce**

1. Start the FabricExample application.
2. Navigate to the "Aware scroll view sticky footer" screen
3. Scroll down. 
4.Attempt to interact with any TextInput component

**Expected behavior**
TextInput components should remain responsive to user input regardless of scrolling

**Screenshots**

**Smartphone (please complete the following information):**
- Desktop OS: [MacOS 14.5]
- Device: [GALAXY S21]
- OS: [Android Version 14]
- RN version: [0.74]
- RN architecture: [fabric]
- JS engine: [Hermes]
- Library version: [1.12.1]

**Additional context**
Using react-native-gesture-handler components restores responsiveness for all touchable components, including TextInputs. However, when a TextInput component from react-native-gesture-handler is used, touching it to input text prevents scrolling of the screen.

I also suspect this is a react-native-reanimated's bug.

**Comment by kirillzyusko** [comment] 2024-05-31 09:22
Hello @NodoPopkhadze 👋 

Actually I think it's a `react-native-reanimated` bug. I've tried to remove all implementation from `KeyboardAwareScrollView` and keep only `KeyboardStickyView` (and bug is still present).

But If I remove `style={styles}` from `KeyboardStickyView` - suddenly everything starts to work 🤔 

I'll try to provide a reproducible example without `keyboard-controller` to `reanimated` repository - but if you want you also can go ahead and provide a reproduction example to `reanimated` repository 🙃

**Comment by NodoPopkhadze** [comment] 2024-06-03 11:03
Hey @kirillzyusko,

I’ve created an issue in the reanimated repository [here](https://github.com/software-mansion/react-native-reanimated/issues/6070). Hopefully, they will respond

**Comment by kirillzyusko** [comment] 2024-06-03 11:22
@NodoPopkhadze awesome ❤️ Thank you very much! 😊 

The only thing is that I would make in **bold** that issue is reproducible **only on real device** (in REA issue).

Can I close this issue? (since we figured out that it's reanimated bug)

**Comment by NodoPopkhadze** [comment] 2024-06-03 11:43
@kirillzyusko Updated.

Yes you can close the issue, since the bug is related to reanimated :)

Thank you.

**Comment by kirillzyusko** [comment] 2024-06-03 11:48
@NodoPopkhadze thank you ❤️ Closing this issue 🙌

**Closed by kirillzyusko** 2024-06-03 11:48 UTC
Labels: 🤖 android, 🏭 fabric, KeyboardStickyView 🩹
