### ISSUE TITLE
Android Split screen support?

### ISSUE THREAD

**Issue by JoniVR** [kirillzyusko/react-native-keyboard-controller#132] opened 2023-03-27 15:08 UTC
**Is your feature request related to a problem? Please describe.**

I can't seem to find a solution to this problem anywhere. I'm developing a tablet application and would like to use an animated keyboard avoiding system. The problem is that something seems to be wrong when reading keyboard height in split screen (2 apps side-by-side) on Android. My guess is that the underlying android Insets mechanism doesn't account for split screen mode or that the implementation doesn't account for it.

The built-in reanimated useAnimatedKeyboard also doesn't support it.

**Describe the solution you'd like**
I'd love to get the correct keyboard height value in split screen mode on Android.

**Describe alternatives you've considered**
The default AdjustResize and AdjustPan options, but these are not the behavior I'm after. Another annoying thing with these solutions is that they don't ignore things like the tab bar, which is lost space when you have a keyboard open.

**Additional context**
Let me know if there's any more info I can provide. I'm not too familiar with the Android Insets api related to this but I do know a bit of iOS/Android Native.

**Comment by kirillzyusko** [comment] 2023-03-27 15:32
@JoniVR is it possible to create a small reproducible example of the issue? Or maybe I can run example app and discover it on a specific device (if so, then is it possible to create android emulator to verify the issue and don't buy a real device 😅)?

**Comment by JoniVR** [comment] 2023-03-27 17:22
Yes, it should be possible on the example using an emulator, I think it should work on an emulator with sdk level > 31. Just long press an app in the bottom bar and select split (right | left). It should be a tablet emulator as well I think. 

I can't check it right now but if you want me to I'll try to create a test scenario tomorrow.

**Comment by JoniVR** [comment] 2023-03-27 21:22
I created a quick demo project. For some reason the height value didn't update live but the video does capture the issue:

https://user-images.githubusercontent.com/7591717/228068241-447afff4-8a25-4268-a1db-19c638f5d6ac.mov

Source code:

`Home.tsx`:
```tsx
import React, {useEffect, useState} from 'react';
import {StyleSheet, TextInput} from 'react-native';
import {
  AndroidSoftInputModes,
  KeyboardController,
  useReanimatedKeyboardAnimation,
} from 'react-native-keyboard-controller';
import Animated, {useAnimatedStyle} from 'react-native-reanimated';

const Home = () => {
  const [textValue, setTextValue] = useState<string>('');
  const {height} = useReanimatedKeyboardAnimation();

  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [{translateY: height.value}],
    };
  }, [height]);

  useEffect(() => {
    KeyboardController.setInputMode(
      AndroidSoftInputModes.SOFT_INPUT_ADJUST_PAN,
    );
  }, []);

  return (
    <Animated.View style={[styles.container, animatedStyle]}>
      <TextInput
        autoFocus
        style={{backgroundColor: 'grey', width: '80%'}}
        value={textValue}
        onChangeText={setTextValue}
      />
    </Animated.View>
  );
};

export default Home;

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

`App.tsx`
```
import React from 'react';
import {KeyboardProvider} from 'react-native-keyboard-controller';
import Home from './Home';

export default function App() {
  return (
    <KeyboardProvider>
      <Home />
    </KeyboardProvider>
  );
}
```

Here's the code: It seems like the height just doesn't change at all (I can't upload directly, so a Dropbox link for now, let me know if you'd prefer a repo instead):

https://www.dropbox.com/s/hpo1exgqzvxm6d5/DemoProject.zip?dl=0

**Comment by kirillzyusko** [comment] 2023-03-28 03:38
@JoniVR thank you for reporting all details. I'll have a look today!

**Comment by kirillzyusko** [comment] 2023-03-28 18:56
@JoniVR I've tested split mode on my Pixel 7 Pro (Android 13). 
It seems like when this mode is activated then Android handles keyboard itself. My observation is:
- if your TextInput stick to bottom of the screen, then Android moves two applications with the animation.
- if your TextInput in a top view has an overlap with a keyboard (when it's opened), then default "adjust*" mechanism will be used
- if the text input in a top view will not have an overlap with a keyboard, then nothing will happen (i.e. views will not be resized/translated)
- interactive keyboard doesn't work if app is shown in splitted mode.
I've tested example app as well as native apps (telegram, official google demo for handling keyboard animations).

Is there a way to know whether an app is opened in split mode? I'm just thinking about kind of "compat mode" (`keyboardDidShow` is still working in this case, so maybe it can be somehow utilized).

**Comment by JoniVR** [comment] 2023-03-28 19:51
> * if your TextInput stick to bottom of the screen, then Android moves two applications with the animation.
> * if your TextInput in a top view has an overlap with a keyboard (when it's opened), then default "adjust*" mechanism will be used

Hmm so if I were to place the textinput from my example at the bottom it would move that textinput up by itself? Was the problem that I expected the entire view to shift? 

So this is different behaviour than I would normally get (since the actual height is not returned by the lib api would be my guess?)

> I've tested example app as well as native apps (telegram, official google demo for handling keyboard animations).

Interesting, how does Telegram, Whatsapp etc handle this? I don't have a physical Android tablet nearby to test atm.

> Is there a way to know whether an app is opened in split mode? I'm just thinking about kind of "compat mode" (`keyboardDidShow` is still working in this case, so maybe it can be somehow utilized).

That sounds pretty great, or at least providing the correct height if that's possible, otherwise it's basically impossible to create a consistent experience (if I understand correctly). I think there is an API for checking splitview, on the activity itself:
https://developer.android.com/reference/android/app/Activity#isInMultiWindowMode()

**Comment by kirillzyusko** [comment] 2023-03-30 11:19
> Interesting, how does Telegram, Whatsapp etc handle this?


https://user-images.githubusercontent.com/22820318/228815676-8b3c3a93-6849-4952-9815-bcdd965979f8.mp4

Here 4 different cases that I described:
- window resizing
- no reaction
- window resizing again
- smooth animation moving the window

As i can understand all of them handled by Android itself.

> That sounds pretty great, or at least providing the correct height if that's possible, otherwise it's basically impossible to create a consistent experience (if I understand correctly). I think there is an API for checking splitview, on the activity itself:
https://developer.android.com/reference/android/app/Activity#isInMultiWindowMode()

Thanks! I'll check it. Right now I'm busy with interactive keyboard feature (I hope to create a new release within ~1-2 weeks) and after that I'll fix switch to fixing of open issues!

> Hmm so if I were to place the textinput from my example at the bottom it would move that textinput up by itself? Was the problem that I expected the entire view to shift?
So this is different behaviour than I would normally get (since the actual height is not returned by the lib api would be my guess?)

Well, it seems like entire window is getting moved. I. e. if your text input is overlapped by keyboard, then it'll move the window (at least you can try to experiment and say how it behaves in your case).
Anyway, for now I think, that it would be really helpful if the API of this lib could return keyboard movement when app is opened in split mode (but it's also worth to make some experiments and get a concrete case of where it's needed, because in your example the TextInput is not overlapped by keyboard, so I think for user experience it's kind of okay to have such layout).
What's your thoughts about this?

**Comment by kirillzyusko** [comment] 2024-01-07 16:23
I still tend to think that the management is already delegated to OS, so whenever text input will be obscured by keyboard - OS will automatically push the input to be above the keyboard. So I don't think it's relevant to handle it on library level.

Thus I'm going to close this issue. Feel free to re-open it or create a new one and provide some proofs and edge cases when OS can not handle it properly 🙂

**Closed by kirillzyusko** 2024-01-07 16:23 UTC
Labels: 🤖 android, feature request 👀
