### ISSUE TITLE
Android: events are no longer received after reload from bundler

### ISSUE THREAD

**Issue by rikardg** [kirillzyusko/react-native-keyboard-controller#113] opened 2023-02-08 17:18 UTC
First, thank you for your work on providing this package, it is much appreciated!

**Issue**

On Android, after a reload from the bundler, the keyboard events are no longer received. Steps to reproduce:

1. Build and start the example Android app from this repo.
2. Go to "3. Events".
3. Activate the text input. A notification is displayed that the keyboard is shown. Hide the keyboard, and a corresponding hide notification is shown.
4. Reload the app from the bundler, e.g. by pressing Cmd/Ctrl+M or via the dev menu.
5. Now repeat from step 2 above, but note that no notifications are displayed, indicating that no events are received.

Expected behaviour is that events are still received after a reload.

**Platform information**

 - Desktop OS: macOS 13.1
 - Device/OS: Android emulator/API level 31, Huawei P10/Android 7.0, and others.
 - RN version: 0.70.5
 - RN architecture: default from example app
 - JS engine: default from example app
 - Library version: 1.4.2

I have not built the example app for iOS, but the events are working properly in the app where the problem was discovered. This seems to be Android specific.

**Comment by kirillzyusko** [comment] 2023-02-09 01:12
Thanks @rikardg 
I will have a look on the problem!

**Comment by kirillzyusko** [comment] 2023-02-09 07:40
I'm able to reproduce a problem. Looking for a solution 👀

**Comment by kirillzyusko** [comment] 2023-02-09 09:17
@rikardg would you mind to check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/114 fixes the issue?

I've tested locally and everything seems to be working fine after these changes, but just want to ask double confirmation 🙂

**Comment by rikardg** [comment] 2023-02-09 13:47
HI!

The unmodified example from the repository works now. 👍 

However, if I move the text input to the front page so that there is no screen navigation before it is displayed, it doesn't work for me on API level 28 and 24. It seems like the first show event is not received after a reload. However, the following hide event as well as subsequent show/hide events are all received. I've tested on:

* Android 7 (24, physical device): first event not received.
* Android 9 (28, physical device and emulator): first event not received.
* Android 12 (31, emulator): first event _is_ received.

To reproduce:

1. Build and run app with the modified `App.tsx` below.
2. Check that show/hide events give a notificiation.
3. Reload app.
4. Focus text input. On Android 7 and 9 (at least), the first show event doesn't give a notification. Check that subsequent events are received (they are for me).

My modified `App.tsx`:

```typescript
import 'react-native-gesture-handler';

import * as React from 'react';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import {
  SafeAreaProvider,
  initialWindowMetrics,
} from 'react-native-safe-area-context';
import Events from './screens/Examples/Events';

const spacerStyle = { marginVertical: 50 };

export default function App() {
  return (
    <SafeAreaProvider initialMetrics={initialWindowMetrics} style={spacerStyle}>
      <KeyboardProvider statusBarTranslucent>
        <Events />
      </KeyboardProvider>
    </SafeAreaProvider>
  );
}
```

**Comment by kirillzyusko** [comment] 2023-02-09 13:53
@rikardg okay, thanks. I will try to test your example tomorrow 👍 
Thanks for great explanation of the issue 😊

**Comment by kirillzyusko** [comment] 2023-02-10 13:27
Hi @rikardg 
I merged one PR and created a new one (https://github.com/kirillzyusko/react-native-keyboard-controller/pull/117), since the issue looks similar from dev perspective, but has absolutely different fixes and I would like to keep them separate just for more transparency
Could you please check if https://github.com/kirillzyusko/react-native-keyboard-controller/pull/117 fixes the problem?
I've rebased this branch on latest `main` branch, so it has both fixes. Hopefully everything should work fine 😊

**Comment by rikardg** [comment] 2023-02-10 17:38
Hi,

I've tested on a few different Android versions now (API level 24/physical, 31/33/emulator) with both the modified example from above as well as the app I'm working on. Works perfectly everywhere. So 👍 from me.

Thank you for fixing this so quickly!

**Comment by kirillzyusko** [comment] 2023-02-11 01:23
@rikardg awesome! Then I will merge PR and will release `1.4.3` in the beginning of next week☺️

**Closed** 2023-02-12 03:53 UTC
Labels: bug, 🤖 android

**Comment by kirillzyusko** [comment] 2023-02-13 11:04
Closed since https://github.com/kirillzyusko/react-native-keyboard-controller/releases/tag/1.4.3 has been published.
