### ISSUE TITLE
Bug Report: bottomOffset Issue with Keyboard Controller in React Native

### ISSUE THREAD

**Issue by dil-nawaz-khan** [kirillzyusko/react-native-keyboard-controller#674] opened 2024-11-05 04:53 UTC
**Describe the bug**
The bottomOffset property in the React Native Keyboard Controller library is not functioning as expected. Despite trying multiple solutions, the space between the focused input field and the keyboard does not increase. This issue persists across various implementations and configurations.

**Code snippet**
type KeyboardAwareViewProps = PropsWithChildren & {
  showToolbar?: boolean;
  scrollEnabled?: boolean;
};

export const KeyboardAwareView = ({
  children,
  showToolbar = true,
  scrollEnabled = false,
}: KeyboardAwareViewProps) => {
  const { bottom } = useSafeAreaInsets();
  return (
    <View style={{ flex: 1 }}>
      <KeyboardAwareScrollView
        scrollEnabled={scrollEnabled}
        nestedScrollEnabled
        keyboardShouldPersistTaps="always"
        bottomOffset={62}
        style={{ flex: 1 }}
        contentContainerStyle={{
          // flexGrow: 1,
          flex: 1,
        }}>
        {children}
      </KeyboardAwareScrollView>
      {showToolbar && <KeyboardToolbar />}
    </View>
  );
};

https://github.com/user-attachments/assets/a0b89be5-fe8f-4733-bfd2-92d70e3648ec

<img width="991" alt="Screenshot 2024-11-05 at 9 45 11 AM" src="https://github.com/user-attachments/assets/d29b57cb-88e7-4b52-8c57-5dee4efea3a7">

**Comment by kirillzyusko** [comment] 2024-11-05 08:36
Hello @dil-nawaz-khan 

This is indeed something strange - it looks like something manages the keyboard (i. e. it's not `keyboard-controller`). Because with `keyboard-controller` the animation runs frame in frame.

Can you post a minimal reproduction example? Or at least a full snippet of `KeyboardAwareView` + your `package.json`?

Additionally I see that you are passing `scrollEnabled={false}` by default. It's incorrect because in this case library will not scroll a `ScrollView`. Additional info can be found here: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/565

**Comment by dil-nawaz-khan** [comment] 2024-11-05 11:52
Hey @kirillzyusko, thanks for your quick response!

The scrollEnabled prop was initially used for another purpose, and I verified that it’s not causing the issue I’m experiencing. I’ve removed that prop from my code snippet below. Good catch! 🫡

I’m using version "react-native-keyboard-controller": "^1.14.3", which is currently the latest one.

I’ve integrated it with a component built for react-hook-form. Could this integration be the reason why the bottomOffset isn’t working as expected?

`Reusable Component Code:`
import { PropsWithChildren } from "react";
import { View } from "react-native";
import {
  KeyboardAwareScrollView,
  KeyboardToolbar,
} from "react-native-keyboard-controller";

type KeyboardAwareViewProps = PropsWithChildren & {
  showToolbar?: boolean;
};

export const KeyboardAwareView = ({
  children,
  showToolbar = true,
}: KeyboardAwareViewProps) => {
  return (
    <View style={{ flex: 1 }}>
      <KeyboardAwareScrollView
        nestedScrollEnabled
        keyboardShouldPersistTaps="always"
        bottomOffset={62}
        style={{ flex: 1 }}
        contentContainerStyle={{ flex: 1 }}
      >
        {children}
      </KeyboardAwareScrollView>
      {showToolbar && <KeyboardToolbar />}
    </View>
  );
};


`How I’m Using It in a Screen:`
 return (
    <KeyboardAwareView>
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ flex: 1 }}>
        <AuthWrapper
          title="Welcome back"
          subTitle="Welcome back! Please enter your details."
          // showLeft={true}
        >
          <View style={styles.container}>
            <View>
              <TextInput
                placeholder="Email"
                name="email"
                label="Email"
                control={control}
              />
              <TextInput
                isPassword
                placeholder="Password"
                name="password"
                label="Password"
                control={control}
              />
            </View>
            <Pressable
              style={styles.forgotPasswordBtn}
              onPress={handleForgotPassword}>
              <Text style={styles.forgotPasswordTxt}>Forgot password</Text>
            </Pressable>
            <View style={styles.btnContainer}>
              <Button
                title="Sign In"
                disabled={loading}
                loading={loading}
                buttonType="primary"
                fill="filled"
                textColor={WHITE_COLOR}
                onPress={handleSubmit(handleSignIn)}
              />
              <Button
                title="Sign In with Google"
                buttonType="icon"
                Icon={Icons.Google}
                fill="shallow"
                onPress={handleGoogle}
              />
            </View>
            <View style={styles.signUpTxtContainer}>
              <Text style={styles.dontHaveAcc}>Don't have an account? </Text>
              <Pressable onPress={handleGoToSignUp}>
                <Text style={styles.signUp}>Sign up</Text>
              </Pressable>
            </View>
          </View>
        </AuthWrapper>
      </ScrollView>
    </KeyboardAwareView>
  );

**Comment by kirillzyusko** [comment] 2024-11-05 12:19
What is the purpose of nesting two `ScrollView`s inside each other? In this case `TextInput` will be associated with plain `ScrollView`, and `KeyboardAwareScrollView` will not work at all (because it will have a different `viewTag`). Can you remove another `ScrollView` - I think it'll start work then 🙂

**Comment by dil-nawaz-khan** [comment] 2024-11-05 12:44
OMG! First of all, this is working like a charm! 🫶🏻🫶🏻 And secondly, I can’t believe I didn’t realize that KeyboardAwareScrollView already provides scrolling functionality.

Thanks, man! You saved me a couple of days of debugging, and I’m reconsidering my plans to quit being a developer! 😆

**Comment by kirillzyusko** [comment] 2024-11-05 12:56
Haha, keep going to be a developer! 💪 

I'm closing this issue, but if you discover that something doesn't work - don't hesitate to open a new issue ❤️ I'll close this one.

**Closed by kirillzyusko** 2024-11-05 12:56 UTC
Labels: 🐛 bug, KeyboardAwareScrollView 📜
