### ISSUE TITLE
KeyboardAwareScrollView scrolling too much when pasting a lot of content in multiline inputibox

### ISSUE THREAD

**Issue by domenicoprestia** [kirillzyusko/react-native-keyboard-controller#348] opened 2024-01-30 08:40 UTC
**Describe the bug**
It happens that when i try to paste a big chunk of text in a multiline TextInput that requires the KeyboardAwareScrollView to scroll, the scroll happens, but it's not as precise as in other times, it looks like it scrolls to much.

**Code snippet**
Cant share code since is a private repo, but its a TextInput inside a KeyboardAwareScrollView

**To Reproduce**

1. Create a KeyboardAwareScrollView with an input component at 3/4 of the screen
2. Try to paste a really big chunk of text

**Expected behavior**

Having the right scroll space without scrolling too much

**Screenshots**

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/46924943/a94133c3-1949-426c-9048-d8b90deec141

**Smartphone (please complete the following information):**

- Desktop OS: [MacOS 10.15.5]
- Device: [e.g. Android Resizable (happens on any android)]
- RN version: [e.g. 0.72.6]
- RN architecture: [old fabric]
- JS engine: [Hermes]
- Library version: [latest]

**Additional context**

**Comment by kirillzyusko** [comment] 2024-01-30 09:04
@domenicoprestia maybe double scroll happens because of "simultaneous" layout & text-change handlers?

Would you mind to try to remove this code:

```tsx
useAnimatedReaction(
      () => input.value,
      (current, previous) => {
        if (
          current?.target === previous?.target &&
          current?.layout.height !== previous?.layout.height
        ) {
          const prevLayout = layout.value;

          layout.value = input.value;
          scrollPosition.value += maybeScroll(keyboardHeight.value, true);
          layout.value = prevLayout;
        }
      },
      [],
    );
```

And see whether it fixes the problem?

**Comment by domenicoprestia** [comment] 2024-01-30 09:06
yes i'll try instantly, in which file can i find it?

**Comment by kirillzyusko** [comment] 2024-01-30 09:08
@domenicoprestia in this: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/components/KeyboardAwareScrollView/index.tsx

**Comment by domenicoprestia** [comment] 2024-01-30 09:16
i've just tried and without that chunk of code it does not scroll when pasting

**Comment by kirillzyusko** [comment] 2024-01-30 09:35
@domenicoprestia doesn't scroll at all or doesn't scroll too much (i. e. expected/desired behavior)? 😅

**Comment by kirillzyusko** [comment] 2024-01-31 19:14
Hi @domenicoprestia 

I've tried to reproduce the problem in example app, but no luck - maybe you can provide a code snippet with minimal reproduction example?

|iOS|Android|
|----|--------|
|<video src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/a2851315-4de8-4f61-8c95-6b2650e233bf">|<video src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/05e49a78-1c83-48b6-80e7-09bec198b5a3">|

**Comment by domenicoprestia** [comment] 2024-02-09 15:10
Sorry, just saw this comment, i'll try to reproduce it again and to give you more background informations on this

**Comment by kirillzyusko** [comment] 2024-06-19 21:37
@domenicoprestia may I ask you which Android version were you using in your tests?

**Comment by kirillzyusko** [comment] 2024-06-24 10:55
@domenicoprestia it could be fixed in latest `1.12.4` version - can you verify, please?

**Comment by iphonic** [comment] 2024-06-25 16:53
@kirillzyusko I am facing a different scroll issue, when text is long and paste on TextInput the scroll won't scroll down, it starts scrolling when you try to scroll couple of time after a fraction of time. Also when we scroll the text manually and try to retype the offset is broken which means the TextInput scrolls up way too much when type. I am using the latest 1.12.4.

**Comment by iphonic** [comment] 2024-06-25 17:32
@kirillzyusko Yes I am doing this 

```
<KeyboardAwareScrollView bottomOffset={40}>
     <View style={{flex:1}}>
          <TextInput
                placeholder={'Compose Your Message'}
                multiline
                style={styles.contentText}
                value={message}
                onChangeText={(value) => setMessage(value)}
           />
     </View>
</KeyboardAwareScrollView>
```

Attached a recording of what's happening, it doesn't allow to scroll up or down, need to do it multiple times.
![Uploading RPReplay_Final1719336468-ezgif.com-video-to-gif-converter.gif…]()

**Comment by kirillzyusko** [comment] 2024-06-25 19:07
@iphonic can you try to replace `KeyboardAwareScrollView` with `ScrollView`? Does the problem with scrolling remains?

On my simulator the problem with scrolling remains - if you scroll outside of the input you can scroll, if you scroll within an input -> it doesn't scroll and it's expected 🤷‍♂️

**Comment by kirillzyusko** [comment] 2024-07-28 11:08
I strongly believe that the issue was fixed in https://github.com/kirillzyusko/react-native-keyboard-controller/commit/21eff3b3372fbd1e7528027b31423ba648512345 and I'm closing the issue. If you discover that the problem still remains, feel free to open a new issue or leave a comment here and I'll re-open the issue.

A small reproduction example will significantly speed up the process of the fix 🚀

**Closed by kirillzyusko** 2024-07-28 11:08 UTC
Labels: 🐛 bug, 📚 components, KeyboardAwareScrollView 📜
