### ISSUE TITLE
[Regression][Android][1.6.0] Content is pushed down when StatusBar is set to transclucent and using native-stack

### ISSUE THREAD

**Issue by thespacemanatee** [kirillzyusko/react-native-keyboard-controller#234] opened 2023-09-09 05:40 UTC
**Describe the bug**

After upgrading to `>=1.6.0`, all my content is pushed below the status bar which defeats the purpose of setting it to be translucent. I believe @kirillzyusko missed this because you tested with `headerShown: true`, but this is not sufficient for the cases where we want to render content below the status bar.

**Code snippet**

```
<StatusBar
  translucent
  backgroundColor="transparent"
/>
```

**Repo for reproducing**

Use `native-stack` with `headerShown` property set to `false` and `statusBarTranslucent` property set to `true`

Let me know if I should provide a repo but the bug should be quite self-explanatory.

**To Reproduce**
1. Set StatusBar to be translucent via one of the following methods:
  - `screenOptions.statusBarTranslucent: true` in native stack
  - `StatusBar.setTranslucent(true)`
  - `<StatusBar translucent />`
2. Make sure that header is set to not show
  - `screenOptions.headerShown: false`
3. See that the content is being pushed below the StatusBar

**Expected behavior**

Content should be rendered under the status bar

**Screenshots**

### Issue

![photo_2023-09-09_13-39-17](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/6837599/e327bc9a-310e-41fd-9f2b-a3442f7ace6f)

### Expected

![photo_2023-09-09_13-39-11](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/6837599/36256bd0-dcd9-4d59-9e6d-02684dd531e6)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13
 - RN version: 0.72.4
 - RN architecture: Paper
 - JS engine: Hermes
 - Library version: 1.6.0 and above

**Comment by kirillzyusko** [comment] 2023-09-09 07:44
@thespacemanatee may I also ask you which version of `react-native-screens` are you using and whether it was changed during RNKC bump?

I will try to reproduce your problem as you described and in case of no luck - I will ask you to provide repro 👀

**Comment by kirillzyusko** [comment] 2023-09-09 08:38
@thespacemanatee by the way - did you specify `statusBarTranslucent` property on `KeyboardProvider` level?

**Comment by thespacemanatee** [comment] 2023-09-09 09:58
@kirillzyusko I'm using `"react-native-screens": "~3.24.0"` and it was not changed when I bumped RNKC.

Specifying `statusBarTranslucent` on `KeyboardProvider` does work! Although this wasn't required on `1.5.8`. Is this a new requirement? What if I want to dynamically switch translucency on and off?

**Comment by kirillzyusko** [comment] 2023-09-09 12:47
> Is this a new requirement?

No, it was a requirement in the past as well 😅 I'm astonished how it worked before in your app 🤔

Basically before I consumed insets of `EdgeToEdge` view (and it was below `rootView`), and if you used `statusBarTranslucent` prop from RNS then I didn't get top insets because they were consumed by the RNS.

However such approach caused some issues - for example sometimes bottom insets by keyboard were not consumed in native stack (and it caused content jump when keyboard is shown), so I started to listen insets from `rootView`.

And now since you didn't specify `statusBarTranslucent` prop - `EdgeToEdge` view adds default paddings.

> What if I want to dynamically switch translucency on and off?

I think now it would be hard to achieve. But if you want to achieve that - you can open an issue and I will try to think how to implement it.

In all apps that I developed we always specified status bar as translucent to match iOS (because on iOS it's always translucent) to simplify cross platform codebase.

But again - if you need to switch on/off translucency, please, open a new issue 🙏

**Comment by kirillzyusko** [comment] 2023-09-11 07:29
@thespacemanatee since specifying `statusBarTranslucent` on `KeyboardProvider` level fixes the problem - I recommend you to go with this solution for now.

I'm going to close this issue - feel free to open a new one if you need dynamic `statusBarTranslucent` 😊

**Closed by kirillzyusko** 2023-09-11 07:29 UTC
Labels: 🐛 bug, 🤖 android
