### ISSUE TITLE
Readme GIF

### ISSUE THREAD

**Issue by hirbod** [kirillzyusko/react-native-keyboard-controller#1] opened 2022-04-25 10:08 UTC
Hi @kirillzyusko,

I just followed your comment on the REA issue and reviewed your package a bit.
Looks very promising. I think it would be nice if you could add a Readme GIF, this usally helps a lot for decision making and give better insight how your module works.

I would love to see the keyboard sync before giving this a try.

Thanks for working on this! It has been years and it is still a pain to handle keyboard and inputs in RN

**Comment by kirillzyusko** [comment] 2022-04-25 10:22
Hi @hirbod 

Thanks for the idea! I will prepare gif (and code for that) today/tomorrow and will upload it to README.

Thank you again for idea :)

**Comment by kirillzyusko** [comment] 2022-04-25 16:17
@hirbod I uploaded gifs. Could you have a look? maybe you will find anything that can be improved?

**Comment by hirbod** [comment] 2022-04-25 16:21
Looks instantly more appealing and inviting. Would optimize the arrangement a little bit for mobile and upload the package as beta or alpha to npm.

From what I see, the package looks very nice and I am going to give it a try.

Is it possible to also manage the scrollview/flatlist with your package? (To adjust insets etc)

![image](https://user-images.githubusercontent.com/504909/165130929-b4f027b3-2123-4d76-8857-bf599227feaa.png)

**Comment by kirillzyusko** [comment] 2022-04-25 17:01
> Is it possible to also manage the scrollview/flatlist with your package? (To adjust insets etc)

I think yes 🙂 I was going to add more examples first and resolve some issues (right now the package conflicts with `react-native-safe-area-view` and they don't work together 😔)

So once I will have more examples and the package will be more stable - yes, I will publish it to `npm`. As of now this package needs to be polished a little bit.

**Comment by hirbod** [comment] 2022-04-25 17:51
Great, can't wait to see the results. Hit me up when you think its stable, would love to integrate this and ditch the terrible keyboard manager by react-native-ui-lib

**Comment by hirbod** [comment] 2022-04-26 09:19
Hi @kirillzyusko,

does is also work with `keyboardDismissMode="interactive"`? If so, also worth a note inside the readme!

**Comment by kirillzyusko** [comment] 2022-04-26 10:10
Hi @hirbod 

I haven't checked it yet, but I will have a look on this prop 👀 Thanks for the suggestion!

**Comment by hirbod** [comment] 2022-04-26 10:16
Fyi: you can set this prop on ScrollView, FlatList, SectionList etc (everything that has a ScrollView underneath). iOS only.

**Comment by kirillzyusko** [comment] 2022-04-26 12:49
@hirbod yes, I know that. I've seen somewhere, that Android v11 also supports closing keyboard using gesture. I haven't played around this API yet, but just thought that it may be good to implement that for both platforms (though I'm not sure yet how).

Not only for a single one :)

**Comment by hirbod** [comment] 2022-04-30 11:33
Sorry @kirillzyusko if I abuse this as a questionary thread, but did you also made sure to test against "native-stack"? (@react-navigation/native-stack together with react-native-screens).

Specially, when working with props like `fullScreenSwipeEnabled`. 
This library has issues for example: https://github.com/douglasjunior/react-native-keyboard-manager

But this library is quite different from yours, since you're trying to more likely solve single input issues (eg Chatviews) and his library looks more like a Keyboard Avoiding Tool

**Comment by kirillzyusko** [comment] 2022-04-30 13:17
Hi @hirbod 

For sure I was going to test how this library works with `native-stack`, because as of now this library is recommended as a default one for building navigators, so I definitely planned to test interoperability between these libraries.

Regarding `react-native-keyboard-manager`... I thought about kind of replicating similar logic in this library too. And I even made an attempt to solve the problem of overlapping keyboard with focused text inputs (you can have a look on `example` project, the example is called `AwareScrollView`). It's still in early development, and I assume it can be changed over time, but part of functionality already works😅

Right now I'm still exploring possibilities of both platforms, as well as various issues when you need to deal with a keyboard and how they were solved using current solutions. So if you have more ideas/issues - don't hesitate to share them☺️ I will add them in my ToDo list👀

BTW, right now I'm trying to add a support for "interactive" dismiss mode. At least I'm experimenting in this direction 😅

**Comment by hirbod** [comment] 2022-04-30 15:30
Sounds very good. Gonna give all of them an intense test soon. Started making a bit of advertisement for this package, looks like the stargaze is increasing :p

**Comment by kirillzyusko** [comment] 2022-04-30 15:55
>  Started making a bit of advertisement for this package, looks like the stargaze is increasing :p

@hirbod ha-ha, thanks! I was pleasantly surprised when I saw how many stars have been added in the last hour. I thought someone is promoting the project. But I didn't know who it was until I reopened this thread 🙈 Thanks again!

**Comment by hirbod** [comment] 2022-04-30 21:33
@kirillzyusko regarding interactive mode: https://github.com/wix/react-native-ui-lib/tree/master/lib/ios/reactnativeuilib/keyboardtrackingview

But please only get inspiration, because this library is far away from being perfect (multiple subviews, only works with one input mounted etc, but that interactive dismissing is working quite good)

**Comment by kirillzyusko** [comment] 2022-05-01 11:44
@hirbod thanks! I will have a look 👀 

Initially I thought to create a replica of keyboard dismissing (through reanimated and gesture-handler). But I will have a look on this implementation as well.

The problem is that on iOS keyboard position is controlled by OS, but on Android 11+ it can be controlled through `setInsetsAndAlpha` method. That's why I thought to create a replica on iOS (and track scroll position through GH) and on Android (using information about scroll position) control it via `setInsetsAndAlpha` method.

But I will investigate this topic more 👀

**Comment by kirillzyusko** [comment] 2022-05-01 14:00
@hirbod I will close this issue, since I've added GIFs (yes, they don't look good on `npm` - I will try to fix it in the next release 😅 ) and uploaded alpha version of the package to [npm](https://www.npmjs.com/package/react-native-keyboard-controller).

If you want to keep a conversation about new features - don't hesitate to open new issues :)
And if you find any bugs - also don't hesitate to report them :)

**Closed by kirillzyusko** 2022-05-01 14:00 UTC

**Comment by hirbod** [comment] 2022-05-01 16:01
You could open the discussion session

**Comment by kirillzyusko** [comment] 2022-05-01 16:55
Nice! I opened one: https://github.com/kirillzyusko/react-native-keyboard-controller/discussions/6
