### ISSUE TITLE
Example with FlatList

### ISSUE THREAD

**Issue by psteinroe** [kirillzyusko/react-native-keyboard-controller#156] opened 2023-05-23 07:54 UTC
**Is your feature request related to a problem? Please describe.**
We are building a chat with your (awesome) package, and it works very smoothly. Thanks! However, at some point, we are experiencing performance issues due to the usage of ScrollView. Is FlatList also supported somehow?

**Describe the solution you'd like**
Add example using FlatList.

**Describe alternatives you've considered**
Using ScrollView, but the performance is bad.

**Comment by kirillzyusko** [comment] 2023-05-23 07:56
@psteinroe What is the issues with FlatList do you experience?

**Comment by psteinroe** [comment] 2023-05-23 07:57
> @psteinroe What is the issues with FlatList do you experience?

That was a swift response! ❤️ I am having troubles getting a chat to work. In your examples, you are inverting views, add fakeViews etc. All this is not really possible FlashList since it uses `renderItem` and does not take children.

**Comment by kirillzyusko** [comment] 2023-05-23 08:29
@psteinroe for adding `fakeView` you can use `ListFooterComponent`/`ListHeaderComponent`. Inverting should work in the same way (i. e. just apply styles to parent view and content style).

**Comment by psteinroe** [comment] 2023-05-23 09:43
that does not work for some reason. It results in some weird and indeterministic behaviours. It seems like applying transform to `contentContainerStyle` does not really work properly since any rotation is lost after navigating. Do you have any ideas? Otherwise, I will put this on hold, and try to create PR with a FlatList example to reproduce.

**Comment by kirillzyusko** [comment] 2023-05-23 10:34
@psteinroe I don't have any ideas. This rotation was used to make `ScrollView` to scroll from bottom to top - you also can achieve this with setting up a `ref` and scrolling to the bottom - https://stackoverflow.com/a/42736127/9272042

Also if you are using `FlashList`, then you may use `renderScrollComponent` prop to specify your custom scroll component (i.e. just use example app code with all transformations/fake views).

**Comment by psteinroe** [comment] 2023-05-23 13:51
@kirillzyusko thanks for the hints. I boiled it down to `rotate: 180deg` not being applied to the children of the `ScrollView`. I now ditched all the transforms and use `scrollToBottom`. This is not optimal as the scrolling process is visible to the user, but it works and is good enough for now. Would be great to find a solution for this, although I understand this is is unrelated to this project.

```tsx
 const scrollViewStyle = useAnimatedStyle(
    () => ({
      height: '100%',
      backgroundColor: '#e2e8f0',
      transform: [{ translateY: height.value }, ...styles.inverted.transform],
    }),
    []
  );

  const textInputStyle = useAnimatedStyle(
    () => ({
      width: '100%',
      transform: [{ translateY: height.value }],
    }),
    []
  );

  const fakeView = useAnimatedStyle(
    () => ({
      height: Math.abs(height.value),
    }),
    []
  );

...

<Reanimated.FlatList
       data={elements ?? []}
        ...
        renderScrollComponent={({ children, ...props }) => (
          <Reanimated.ScrollView
            {...props}
            style={scrollViewStyle}
            showsVerticalScrollIndicator={false}
          >
            <View style={styles.inverted}>
              <Reanimated.View style={fakeView} />
              {children}
            </View>
          </Reanimated.ScrollView>
        )}
      />

```

**Comment by kirillzyusko** [comment] 2023-05-23 14:33
@psteinroe you can show full-screen spinner, while the chat-component is getting mounted (it should overlap the content). In this case user will not notice scrolling process 🙂 

The code that you've shared - doesn't it work? It seems like it should 🙂

**Comment by psteinroe** [comment] 2023-05-23 14:35
> @psteinroe you can show full-screen spinner, while the chat-component is getting mounted (it should overlap the content). In this case user will not notice scrolling process 🙂

thanks, will do!


> The code that you've shared - doesn't it work? It seems like it should 🙂

it does not unfortunately. I played with this for a while, and `<View style={styles.inverted}>...</View>` does not apply the transform to children. I assume this is because of the way `FlatList` works... Could not figure out a way around that.

**Comment by kirillzyusko** [comment] 2023-05-23 14:46
@psteinroe got it! I will have a look when I get time 👍

**Comment by kirillzyusko** [comment] 2023-06-06 11:19
@MarceloPrado good point! This rotation was needed for 2 purposes:

- to scroll list from the end to beginning;
- to achieve smooth keyboard transition (since I'm adding fakeView in the beginning of the list to add space for scrolling - without this transformation the transition looks a little bit twitchy -> https://github.com/kirillzyusko/react-native-keyboard-controller/pull/76 and https://github.com/kirillzyusko/react-native-keyboard-controller/pull/112 for reference).

**Comment by timothyerwin** [comment] 2023-07-12 06:52
is there any fix for this? I'm trying to use it with a flatlist but none of the onmove or interactive events fire when using dismiss interactive

**Comment by timothyerwin** [comment] 2023-07-12 06:55
it would be great if the keyboard hook just gave the frame height position of the keyboard in ios without being related to any scrollview...is that possible?

**Comment by kirillzyusko** [comment] 2023-07-12 06:56
Hello @timothyerwin 
I don't think missing onMove/onInteractive events can depend on a FlatList usage. Most likely the problem is in something else - feel free to create a new issue with minimal reproduction example☺️

**Comment by timothyerwin** [comment] 2023-07-12 06:58
onMove works fine when opening and closing the keyboard, but as soon as you try to interactively close the keyboard in a flatlist with `keyboardDismissMode="interactive"` it will not report any event at all.

**Comment by kirillzyusko** [comment] 2023-07-12 06:58
> it would be great if the keyboard hook just gave the frame height position of the keyboard as it moves interactively in ios without being related to any scrollview...is that possible?

If I understand your question correctly - that's exactly what keyboard hook does. You can try to run example app - I have an example with interactive keyboard there.

**Comment by kirillzyusko** [comment] 2023-07-12 07:00
> onMove works fine when opening and closing the keyboard, but as soon as you try to interactively close the keyboard in a flatlist with keyboardDismissMode="interactive" it will not report any event at all.

@timothyerwin Please, create a new issue with reproduction repo ☺️

**Comment by timothyerwin** [comment] 2023-07-12 17:09
@kirillzyusko really appreciate your quick follow up last night. it really helped me dive in and figure out the problem. this is the perfect library for managing the keyboard frames in ios I must say. a real gem!

so, back to the problem...I was able to isolate it by adding a tab in my app with a minimal example after I ran your examples and saw it indeed worked as you said. once I got it working in my isolated example I figured out that for some strange reason I needed to add an explicit height on the view that contained the text input otherwise it would not report the interactive events. I'm not sure if that's mentioned anywhere here in the docs, or something that could be solved in this library but it's worth spelling out in the docs.

once again, thanks so much for a great library!

**Comment by kirillzyusko** [comment] 2023-07-12 18:06
@timothyerwin glad you found a problem!

> I'm not sure if that's mentioned anywhere here in the docs, or something that could be solved in this library but it's worth spelling out in the docs.

Could you please share a code snippet where issue you mention is reproducible? I'm afraid I still don't understand the problem and of course if it's known problem/issue I'd like to highlight it in docs 😊

**Closed** 2023-09-14 14:05 UTC
Labels: example
